# Generated by Django 4.2.4 on 2024-02-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pets',
            field=models.ManyToManyField(blank=True, to='pets.pet'),
        ),
    ]
